# Generated by Django 3.2.8 on 2021-10-31 10:26

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('clinic_id', models.IntegerField()),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('clinic_type', models.CharField(choices=[('clinic', 'Clinic'), ('ambulance', 'Ambulance')], default='clinic', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalClinic',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('clinic_id', models.IntegerField()),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('clinic_type', models.CharField(choices=[('clinic', 'Clinic'), ('ambulance', 'Ambulance')], default='clinic', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical clinic',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
