# Generated by Django 3.2.9 on 2021-11-30 14:44

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_id', models.IntegerField(help_text='UNIS Kód', unique=True)),
                ('abbreviation', models.CharField(help_text='Zkratka', max_length=10)),
                ('description', models.CharField(db_index=True, help_text='Název', max_length=255)),
                ('is_hospital', models.BooleanField(default=True, help_text='Ambulance')),
                ('is_ambulance', models.BooleanField(default=False, help_text='Lůžkové oddělení')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('clinic_external_id', models.IntegerField(help_text='UNIS Kód kliniky')),
                ('external_id', models.IntegerField(help_text='UNIS Kód', unique=True)),
                ('abbreviation', models.CharField(help_text='Zkratka', max_length=10)),
                ('description', models.CharField(help_text='Název', max_length=255)),
                ('specialty', models.CharField(help_text='Odbornost', max_length=255)),
                ('icp', models.CharField(help_text='IČP', max_length=255)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('code_sukl', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAdverseEffect',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical adverse effect',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClinic',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_id', models.IntegerField(db_index=True, help_text='UNIS Kód')),
                ('abbreviation', models.CharField(help_text='Zkratka', max_length=10)),
                ('description', models.CharField(db_index=True, help_text='Název', max_length=255)),
                ('is_hospital', models.BooleanField(default=True, help_text='Ambulance')),
                ('is_ambulance', models.BooleanField(default=False, help_text='Lůžkové oddělení')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical clinic',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDepartment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('clinic_external_id', models.IntegerField(help_text='UNIS Kód kliniky')),
                ('external_id', models.IntegerField(db_index=True, help_text='UNIS Kód')),
                ('abbreviation', models.CharField(help_text='Zkratka', max_length=10)),
                ('description', models.CharField(help_text='Název', max_length=255)),
                ('specialty', models.CharField(help_text='Odbornost', max_length=255)),
                ('icp', models.CharField(help_text='IČP', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical department',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDiagnosis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Diagnosis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDrug',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('code_sukl', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical drug',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIdentification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, help_text='Název zdravotnického zařízení', max_length=100)),
                ('shortcut', models.CharField(blank=True, db_index=True, help_text='Zkratka', max_length=20, null=True)),
                ('identifier', models.IntegerField(help_text='Identifikační číslo zařízení')),
                ('address', models.CharField(blank=True, help_text='Ulice', max_length=100)),
                ('zip', models.CharField(help_text='PSČ', max_length=20)),
                ('city', models.CharField(help_text='Město', max_length=50)),
                ('ico', models.CharField(blank=True, help_text='IČO', max_length=20)),
                ('dic', models.CharField(blank=True, help_text='DIČ', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical identification',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInsuranceCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(db_index=True, help_text='Kód', max_length=20)),
                ('name', models.CharField(db_index=True, help_text='Název', max_length=255)),
                ('shortcut', models.CharField(blank=True, db_index=True, help_text='Zkratka', max_length=20, null=True)),
                ('address', models.CharField(blank=True, help_text='Ulice', max_length=100)),
                ('zip', models.CharField(help_text='PSČ', max_length=20)),
                ('city', models.CharField(help_text='Město', max_length=50)),
                ('ico', models.CharField(blank=True, help_text='IČO', max_length=20)),
                ('dic', models.CharField(blank=True, help_text='DIČ', max_length=20)),
                ('databox', models.CharField(blank=True, help_text='Databox', max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Insurance Company',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('person_number', models.CharField(db_index=True, help_text='Osobní číslo', max_length=100)),
                ('name', models.CharField(help_text='Jméno', max_length=255)),
                ('f_title', models.CharField(default='', help_text='Titul před', max_length=100)),
                ('l_title', models.CharField(default='', help_text='Titul za', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical person',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical tag',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Název zdravotnického zařízení', max_length=100, unique=True)),
                ('shortcut', models.CharField(blank=True, help_text='Zkratka', max_length=20, null=True, unique=True)),
                ('identifier', models.IntegerField(help_text='Identifikační číslo zařízení')),
                ('address', models.CharField(blank=True, help_text='Ulice', max_length=100)),
                ('zip', models.CharField(help_text='PSČ', max_length=20)),
                ('city', models.CharField(help_text='Město', max_length=50)),
                ('ico', models.CharField(blank=True, help_text='IČO', max_length=20)),
                ('dic', models.CharField(blank=True, help_text='DIČ', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='Kód', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Název', max_length=255, unique=True)),
                ('shortcut', models.CharField(blank=True, help_text='Zkratka', max_length=20, null=True, unique=True)),
                ('address', models.CharField(blank=True, help_text='Ulice', max_length=100)),
                ('zip', models.CharField(help_text='PSČ', max_length=20)),
                ('city', models.CharField(help_text='Město', max_length=50)),
                ('ico', models.CharField(blank=True, help_text='IČO', max_length=20)),
                ('dic', models.CharField(blank=True, help_text='DIČ', max_length=20)),
                ('databox', models.CharField(blank=True, help_text='Databox', max_length=10)),
            ],
            options={
                'verbose_name': 'Insurance Company',
                'verbose_name_plural': 'Insurance Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('person_number', models.CharField(help_text='Osobní číslo', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Jméno', max_length=255)),
                ('f_title', models.CharField(default='', help_text='Titul před', max_length=100)),
                ('l_title', models.CharField(default='', help_text='Titul za', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='references__name_1a56d8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='references__name_5f7174_idx'),
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='references.tag'),
        ),
    ]
