# Generated by Django 3.2.9 on 2021-12-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_diagnoses_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='atc_group',
            field=models.CharField(blank=True, help_text='ATC skupina', max_length=255),
        ),
        migrations.AddField(
            model_name='drug',
            name='name_supplement',
            field=models.CharField(blank=True, help_text='Doplněk názvu', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='atc_group',
            field=models.CharField(blank=True, help_text='ATC skupina', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldrug',
            name='name_supplement',
            field=models.CharField(blank=True, help_text='Doplněk názvu', max_length=255),
        ),
        migrations.AlterField(
            model_name='drug',
            name='code_sukl',
            field=models.CharField(help_text='Kód SÚKL', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(help_text='Název léku', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='code_sukl',
            field=models.CharField(db_index=True, help_text='Kód SÚKL', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldrug',
            name='name',
            field=models.CharField(help_text='Název léku', max_length=255),
        ),
    ]
