# Generated by Django 3.2.9 on 2021-12-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, help_text='Obrázek', null=True, upload_to='clinics'),
        ),
        migrations.AddField(
            model_name='historicalclinic',
            name='image',
            field=models.TextField(blank=True, help_text='Obrázek', max_length=100, null=True),
        ),
    ]
