# Generated by Django 3.2.11 on 2022-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_insurance_company_allow_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinsurancecompany',
            name='shortcut',
            field=models.CharField(blank=True, help_text='Zkratka', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='shortcut',
            field=models.CharField(blank=True, help_text='Zkratka', max_length=20, null=True),
        ),
    ]
