# Generated by Django 3.2.11 on 2022-01-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_insurance_company_shortcut_unuque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='historicaldepartment',
            name='specialty',
        ),
        migrations.AddField(
            model_name='department',
            name='specialization_code',
            field=models.CharField(blank=True, help_text='Odbornost (kód)', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='specialization_code',
            field=models.CharField(blank=True, help_text='Odbornost (kód)', max_length=255),
        ),
    ]
