# Generated by Django 3.2.11 on 2022-01-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_department_specialization_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='for_insurance',
            field=models.BooleanField(blank=True, help_text='Používat pro vykazování pojištění', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='ns',
            field=models.CharField(blank=True, help_text='Nákladove středisko', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='for_insurance',
            field=models.BooleanField(blank=True, db_index=True, help_text='Používat pro vykazování pojištění', null=True),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='ns',
            field=models.CharField(blank=True, help_text='Nákladove středisko', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalidentification',
            name='for_insurance',
            field=models.BooleanField(blank=True, db_index=True, help_text='Používat pro vykazování pojištění', null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='for_insurance',
            field=models.BooleanField(blank=True, help_text='Používat pro vykazování pojištění', null=True, unique=True),
        ),
    ]
