# Generated by Django 3.2.11 on 2022-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0010_add_reports_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='external_id',
            field=models.IntegerField(blank=True, help_text='UNIS Kód', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='external_id',
            field=models.IntegerField(blank=True, help_text='UNIS Kód', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalclinic',
            name='external_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='UNIS Kód', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='external_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='UNIS Kód', null=True),
        ),
    ]
