# Generated by Django 3.2.11 on 2022-01-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_medical_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinsurancecompany',
            name='type',
            field=models.CharField(blank=True, help_text='Druh pojistného vztahu', max_length=20),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='type',
            field=models.CharField(blank=True, help_text='Druh pojistného vztahu', max_length=20),
        ),
    ]
