# Generated by Django 3.2.11 on 2022-01-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_insurance_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalidentification',
            name='identifier',
            field=models.CharField(blank=True, help_text='Identifikační číslo zařízení', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='identifier',
            field=models.CharField(blank=True, help_text='Identifikační číslo zařízení', max_length=20, null=True),
        ),
    ]
