# Generated by Django 3.2.11 on 2022-02-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0014_identification_identifier_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Klinika', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.clinic'),
        ),
        migrations.AlterField(
            model_name='department',
            name='clinic_external_id',
            field=models.IntegerField(blank=True, help_text='UNIS Kód kliniky', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='clinic_external_id',
            field=models.IntegerField(blank=True, help_text='UNIS Kód kliniky', null=True),
        ),
    ]
