# Generated by Django 3.2.11 on 2022-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_department_clinic_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icp',
            field=models.CharField(help_text='IČP', max_length=8),
        ),
        migrations.AlterField(
            model_name='department',
            name='ns',
            field=models.CharField(blank=True, help_text='Nákladove středisko', max_length=6),
        ),
        migrations.AlterField(
            model_name='department',
            name='specialization_code',
            field=models.CharField(blank=True, help_text='Odbornost (kód)', max_length=7),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='icp',
            field=models.CharField(help_text='IČP', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='ns',
            field=models.CharField(blank=True, help_text='Nákladove středisko', max_length=6),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='specialization_code',
            field=models.CharField(blank=True, help_text='Odbornost (kód)', max_length=7),
        ),
        migrations.AlterField(
            model_name='historicalidentification',
            name='identifier',
            field=models.CharField(blank=True, help_text='Identifikační číslo zařízení', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='identifier',
            field=models.CharField(blank=True, help_text='Identifikační číslo zařízení', max_length=8, null=True),
        ),
    ]
