# Generated by Django 3.2.11 on 2022-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_references_length_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='specialization_code',
            field=models.CharField(blank=True, help_text='Odbornost (kód)', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='specialization_code',
            field=models.CharField(blank=True, help_text='Odbornost (kód)', max_length=3),
        ),
    ]
