# Generated by Django 3.2.11 on 2022-02-07 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_udpate_url_parameters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0017_department_specialization_constrants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('icp', models.CharField(help_text='IČP', max_length=8, unique=True)),
                ('organization', models.CharField(help_text='Název organizace (zařízení)', max_length=255)),
                ('department', models.CharField(blank=True, help_text='Název oddělení', max_length=255)),
                ('specialization_code', models.CharField(blank=True, help_text='Odbornost (kód)', max_length=3)),
            ],
            options={
                'ordering': ['organization'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalExternalDepartment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('icp', models.CharField(db_index=True, help_text='IČP', max_length=8)),
                ('organization', models.CharField(help_text='Název organizace (zařízení)', max_length=255)),
                ('department', models.CharField(blank=True, help_text='Název oddělení', max_length=255)),
                ('specialization_code', models.CharField(blank=True, help_text='Odbornost (kód)', max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='references.externaldepartment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update')),
            ],
            options={
                'verbose_name': 'historical external department',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
