# Generated by Django 3.2.12 on 2022-03-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_clinic_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidentification',
            name='pcz',
            field=models.CharField(blank=True, help_text='Pořadové číslo začleněného zařízení', max_length=3),
        ),
        migrations.AddField(
            model_name='identification',
            name='pcz',
            field=models.CharField(blank=True, help_text='Pořadové číslo začleněného zařízení', max_length=3),
        ),
    ]
