# Generated by Django 3.2.12 on 2022-03-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0022_department_provider_workplace_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='provider_code',
        ),
        migrations.RemoveField(
            model_name='historicaldepartment',
            name='provider_code',
        ),
    ]
