# Generated by Django 3.2.8 on 2021-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0002_clinics'),
        ('users', '0002_auto_20211017_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinics',
            field=models.ManyToManyField(to='ipharm.Clinic', verbose_name='My clinics'),
        ),
    ]
