FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ARG REQUIREMENTS_FILE=base.txt

WORKDIR /app
COPY requirements/${REQUIREMENTS_FILE} /app/

RUN pip install -r ${REQUIREMENTS_FILE}

