version: "3"
services:
  app:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: base.txt
    container_name: ipharm_web
    image: conceptica/ipharm_web
    volumes:
      - .:/app
    depends_on:
      - postgres
    privileged: true
    env_file:
      - ./.envs/.local/.app
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: scripts/start.sh

  postgres:
    container_name: ipharm_postgres
    image: postgres:13.4-alpine
    env_file:
      - ./.envs/.local/.postgres
