version: "3"
services:
  ipharm_app:
    container_name: ipharm_app
    image: conceptica/ipharm_app:local
    depends_on:
      - ipharm_postgres
    env_file:
      - .envs/.development/.ipharm_app
      - .envs/.development/.ipharm_postgres
    ports:
      - "8000:8000"
    command: scripts/start.sh

  ipharm_postgres:
    container_name: ipharm_postgres
    image: postgres:13.4-alpine
    env_file:
      - .envs/.development/.ipharm_postgres
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data
