version: "3"
services:
  ipharm-app:
    build:
      context: .
      dockerfile: dockerfiles/development/Dockerfile
    container_name: ipharm_dev
    image: ipharm_dev
    volumes: &volumes-ipharm-app
      - .:/app
    logging: &logging
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    depends_on:
      - ipharm-postgres
    env_file: &envs-ipharm-app
      - .envs/.development/.ipharm_app
      - .envs/.development/.ipharm_postgres
      - .envs/.development/.ipharm_redis
    ports:
      - "8000:8000"
    command: scripts/start.sh

  ipharm-worker-high-priority:
    container_name: ipharm_worker_high_priority
    image: ipharm_dev
    volumes: *volumes-ipharm-app
    logging: *logging
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    command: scripts/start_worker.sh  -Q high_priority -n high_priority

  ipharm-worker-medium-priority:
    container_name: ipharm_worker_medium_priority
    image: ipharm_dev
    volumes: *volumes-ipharm-app
    logging: *logging
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    command: scripts/start_worker.sh  -Q medium_priority -n medium_priority

  ipharm-worker-low-priority:
    container_name: ipharm_worker_low_priority
    image: ipharm_dev
    volumes: *volumes-ipharm-app
    logging: *logging
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    command: scripts/start_worker.sh  -Q low_priority -n low_priority

  ipharm-beat:
    container_name: ipharm_beat_dev
    image: ipharm_dev
    volumes: *volumes-ipharm-app
    depends_on:
      - ipharm-postgres
      - ipharm-redis
      - ipharm-app
    env_file: *envs-ipharm-app
    command: scripts/start_beat.sh
    logging: *logging

  ipharm-postgres:
    container_name: ipharm_postgres
    image: postgres:13.4-alpine
    env_file:
      - .envs/.development/.ipharm_postgres
    volumes:
      - ./_postgres_data_ipharm:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ipharm-redis:
    container_name: ipharm_redis
    image: redis:6.2-alpine

  ipharm-flower:
    image: mher/flower
    container_name: ipharm_flower
    env_file:
      -  .envs/.development/.ipharm_redis
    ports:
      - "5555:5555"
    depends_on:
      - ipharm-redis

  iciselniky-app:
    container_name: iciselniky_app
    image: conceptica/iciselniky_app:local
    logging: *logging
    depends_on:
      - iciselniky-postgres
    env_file: &envs-iciselniky-app
      - .envs/.development/.iciselniky_app
      - .envs/.development/.iciselniky_postgres
      - .envs/.development/.iciselniky_redis
    ports:
      - "8001:8000"
    command: scripts/start.sh
    volumes: &volumes-iciselniky-app
      - ./iciselniky_static:/app/static

  iciselniky-postgres:
    container_name: iciselniky_postgres
    image: postgres:13.4-alpine
    env_file:
      - .envs/.development/.iciselniky_postgres
    volumes:
      - ./_postgres_data_iciselniky:/var/lib/postgresql/data

  iciselniky-worker:
    container_name: iciselniky_worker
    image: conceptica/iciselniky_app:local
    volumes: *volumes-iciselniky-app
    logging: *logging
    depends_on:
      - iciselniky-postgres
      - iciselniky-redis
      - iciselniky-app
    env_file: *envs-iciselniky-app
    command: scripts/start_worker.sh

  iciselniky-beat:
    container_name: iciselniky_beat
    image: conceptica/iciselniky_app:local
    volumes: *volumes-iciselniky-app
    depends_on:
      - iciselniky-postgres
      - iciselniky-redis
      - iciselniky-app
    env_file: *envs-iciselniky-app
    command: scripts/start_beat.sh
    logging: *logging

  iciselniky-redis:
    container_name: iciselniky_redis
    image: redis:6.2-alpine

  iciselniky-flower:
    image: mher/flower
    container_name: iciselniky_flower
    env_file:
      -  .envs/.development/.iciselniky_redis
    ports:
      - "5556:5555"
    depends_on:
      - iciselniky-redis

  ipharm-frontend:
    image: conceptica/ipharm_fe_app:local
    container_name: ipharm-frontend-app
    command: cp -r ./build /frontend
    logging: *logging
    volumes:
      - ./frontend_ipharm:/frontend

  kerberos:
    image: conceptica/test_kerberos_server
    ports:
      - "88:88"
      - "750:750"
    volumes:
      - ./keytab:/app/keytab
    env_file:
      - .envs/.development/.kerberos

  apache:
    image: conceptica/apache_kerberos:latest
    volumes:
        - ./apache-config/:/app/config/
        - ./keytab:/app/keytab
        - ./static:/app/static
        - ./frontend_ipharm:/frontend_ipharm
    ports:
      - "80:80"
    env_file: .envs/.development/.apache
    depends_on:
      - kerberos
