from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from .views import (
    cares,
    checkins,
    patient_informations,
    patients,
    persons,
    pharmacological_evaluations,
    pharmacological_plans,
    risk_drug_histories,
)

app_name = "ipharm"

urlpatterns = [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="ipharm:schema"),
        name="swagger-ui",
    ),
    path("patients/", patients.PatientListView.as_view(), name="patient_list"),
    path(
        "patients/<int:pk>/",
        patients.PatientDetailView.as_view(),
        name="patient_detail",
    ),
    path(
        "patients/<int:pk>/history/",
        patients.PatientHistoryView.as_view(),
        name="patient_history",
    ),
    path(
        "cares/<int:pk>/",
        cares.CareDetailView.as_view(),
        name="care_detail",
    ),
    path(
        "cares/<int:pk>/history/",
        cares.CareHistoryView.as_view(),
        name="care_history",
    ),
    path("checkins/", checkins.CheckInListView.as_view(), name="checkin_list"),
    path(
        "checkins/<int:pk>/",
        checkins.CheckInDetailView.as_view(),
        name="checkin_detail",
    ),
    path(
        "checkins/<int:pk>/history/",
        checkins.CheckInHistoryView.as_view(),
        name="checkin_history",
    ),
    path(
        "risk-drug-histories/",
        risk_drug_histories.RiskDrugHistoryListView.as_view(),
        name="risk_drug_history_list",
    ),
    path(
        "risk-drug-histories/<int:pk>/",
        risk_drug_histories.RiskDrugHistoryDetailView.as_view(),
        name="risk_drug_history_detail",
    ),
    path(
        "risk-drug-histories/<int:pk>/history/",
        risk_drug_histories.RiskDrugHistoryHistoryView.as_view(),
        name="risk_drug_history_history",
    ),
    path(
        "risk-drug-history-comments/",
        risk_drug_histories.RiskDrugHistoryCommentListView.as_view(),
        name="risk_drug_history_comment_list",
    ),
    path(
        "risk-drug-history-comments/<int:pk>/",
        risk_drug_histories.RiskDrugHistoryCommentDetailView.as_view(),
        name="risk_drug_history_comment_detail",
    ),
    path(
        "risk-drug-history-comments/<int:pk>/history/",
        risk_drug_histories.RiskDrugHistoryCommentHistoryView.as_view(),
        name="risk_drug_history_comment_history",
    ),
    path(
        "patient-informations/",
        patient_informations.PatientInformationListView.as_view(),
        name="patient_information_list",
    ),
    path(
        "patient-informations/<int:pk>/",
        patient_informations.PatientInformationDetailView.as_view(),
        name="patient_information_detail",
    ),
    path(
        "patient-informations/<int:pk>/history/",
        patient_informations.PatientInformationHistoryView.as_view(),
        name="patient_information_history",
    ),
    path(
        "pharmacological-evaluations/",
        pharmacological_evaluations.PharmacologicalEvaluationListView.as_view(),
        name="pharmacological_evaluation_list",
    ),
    path(
        "pharmacological-evaluations/<int:pk>/",
        pharmacological_evaluations.PharmacologicalEvaluationDetailView.as_view(),
        name="pharmacological_evaluation_detail",
    ),
    path(
        "pharmacological-evaluations/<int:pk>/history/",
        pharmacological_evaluations.PharmacologicalEvaluationHistoryView.as_view(),
        name="pharmacological_evaluation_history",
    ),
    path(
        "pharmacological-evaluation-comments/",
        pharmacological_evaluations.PharmacologicalEvaluationCommentListView.as_view(),
        name="pharmacological_evaluation_comment_list",
    ),
    path(
        "pharmacological-evaluation-comments/<int:pk>/",
        pharmacological_evaluations.PharmacologicalEvaluationCommentDetailView.as_view(),
        name="pharmacological_evaluation_comment_detail",
    ),
    path(
        "pharmacological-evaluation-comments/<int:pk>/history/",
        pharmacological_evaluations.PharmacologicalEvaluationCommentHistoryView.as_view(),
        name="pharmacological_evaluation_comment_history",
    ),
    path(
        "pharmacological-plans/",
        pharmacological_plans.PharmacologicalPlanListView.as_view(),
        name="pharmacological_plan_list",
    ),
    path(
        "pharmacological-plans/<int:pk>/",
        pharmacological_plans.PharmacologicalPlanDetailView.as_view(),
        name="pharmacological_plan_detail",
    ),
    path(
        "pharmacological-plans/<int:pk>/history/",
        pharmacological_plans.PharmacologicalPlanHistoryView.as_view(),
        name="pharmacological_plan_history",
    ),
    path(
        "pharmacological-plan-comments/",
        pharmacological_plans.PharmacologicalPlanCommentListView.as_view(),
        name="pharmacological_plan_comment_list",
    ),
    path(
        "pharmacological-plan-comments/<int:pk>/",
        pharmacological_plans.PharmacologicalPlanCommentDetailView.as_view(),
        name="pharmacological_plan_comment_detail",
    ),
    path(
        "pharmacological-plan-comments/<int:pk>/history/",
        pharmacological_plans.PharmacologicalPlanCommentHistoryView.as_view(),
        name="pharmacological_plan_comment_history",
    ),
]
