# Generated by Django 3.2.9 on 2021-11-27 16:15

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('care_type', models.CharField(choices=[('hospitalization', 'Hospitalization'), ('ambulation', 'Ambulation')], default='ambulation', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='UNIS ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('polypharmacy', models.BooleanField(default=False, help_text='Polypragmazie')),
                ('polypharmacy_note', models.TextField(blank=True, help_text='Poznámka k polypragmazii', verbose_name='poznámka k polypragmazii')),
                ('high_interaction_potential', models.BooleanField(default=False, help_text='Léčiva s vysokým interakčním potenciálem', verbose_name='polypragmazie')),
                ('high_interaction_potential_note', models.TextField(blank=True, help_text='Poznámka k léčivám s vysokým interakčním potenciálem')),
                ('renal_insufficiency', models.BooleanField(default=False, help_text='Renální insuficience')),
                ('renal_insufficiency_note', models.TextField(blank=True, help_text='Poznámka k renální insuficience')),
                ('significant_biochemical_changes', models.BooleanField(default=False, help_text='Další významné změny biochemických nebo hematolologických parametrů')),
                ('significant_biochemical_changes_note', models.TextField(blank=True, help_text='Poznámka k dalším významným změnám biochemických nebo hematolologických parametrů')),
                ('systemic_corticosteroids', models.BooleanField(default=False, help_text='Systémové kortikoidy nebo jiné imunosupresiva')),
                ('systemic_corticosteroids_note', models.TextField(blank=True, help_text='Poznámka k systémovým kortikoidům nebo jiným imunosupresivům')),
                ('narrow_therapeutic_window', models.BooleanField(default=False, help_text='Léčiva s úzkým terapeutickým oknem')),
                ('narrow_therapeutic_window_note', models.TextField(blank=True, help_text='Poznámka k léčivům s úzkým terapeutickým oknem')),
                ('hepatic_insufficiency', models.BooleanField(default=False, help_text='Laboratorní známky hepatální insuficience')),
                ('hepatic_insufficiency_note', models.TextField(blank=True, help_text='Poznámka k laboratorním známkám hepatální insuficience')),
                ('intensive_care', models.BooleanField(default=False, help_text='Pacient v intenzivní péči')),
                ('intensive_care_note', models.TextField(blank=True, help_text='Poznámka k intenzivní péči')),
                ('pharmacist_intervention_required', models.BooleanField(default=False, help_text='Nutný zásah klinického farmaceuta')),
                ('consultation_requested', models.BooleanField(default=False, help_text='Vyžádané konzilium')),
                ('risk_level', models.CharField(choices=[('1', '1. stupeň'), ('2', '2. stupeň'), ('3', '3. stupeň')], default='1', help_text='Výsledný stupeň rizikovosti', max_length=1)),
                ('patient_condition_change', models.BooleanField(default=False, help_text='Změna stavu pacienta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dekurz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('made_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCare',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('care_type', models.CharField(choices=[('hospitalization', 'Hospitalization'), ('ambulation', 'Ambulation')], default='ambulation', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='UNIS ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical care',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCheckIn',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('polypharmacy', models.BooleanField(default=False, help_text='Polypragmazie')),
                ('polypharmacy_note', models.TextField(blank=True, help_text='Poznámka k polypragmazii', verbose_name='poznámka k polypragmazii')),
                ('high_interaction_potential', models.BooleanField(default=False, help_text='Léčiva s vysokým interakčním potenciálem', verbose_name='polypragmazie')),
                ('high_interaction_potential_note', models.TextField(blank=True, help_text='Poznámka k léčivám s vysokým interakčním potenciálem')),
                ('renal_insufficiency', models.BooleanField(default=False, help_text='Renální insuficience')),
                ('renal_insufficiency_note', models.TextField(blank=True, help_text='Poznámka k renální insuficience')),
                ('significant_biochemical_changes', models.BooleanField(default=False, help_text='Další významné změny biochemických nebo hematolologických parametrů')),
                ('significant_biochemical_changes_note', models.TextField(blank=True, help_text='Poznámka k dalším významným změnám biochemických nebo hematolologických parametrů')),
                ('systemic_corticosteroids', models.BooleanField(default=False, help_text='Systémové kortikoidy nebo jiné imunosupresiva')),
                ('systemic_corticosteroids_note', models.TextField(blank=True, help_text='Poznámka k systémovým kortikoidům nebo jiným imunosupresivům')),
                ('narrow_therapeutic_window', models.BooleanField(default=False, help_text='Léčiva s úzkým terapeutickým oknem')),
                ('narrow_therapeutic_window_note', models.TextField(blank=True, help_text='Poznámka k léčivům s úzkým terapeutickým oknem')),
                ('hepatic_insufficiency', models.BooleanField(default=False, help_text='Laboratorní známky hepatální insuficience')),
                ('hepatic_insufficiency_note', models.TextField(blank=True, help_text='Poznámka k laboratorním známkám hepatální insuficience')),
                ('intensive_care', models.BooleanField(default=False, help_text='Pacient v intenzivní péči')),
                ('intensive_care_note', models.TextField(blank=True, help_text='Poznámka k intenzivní péči')),
                ('pharmacist_intervention_required', models.BooleanField(default=False, help_text='Nutný zásah klinického farmaceuta')),
                ('consultation_requested', models.BooleanField(default=False, help_text='Vyžádané konzilium')),
                ('risk_level', models.CharField(choices=[('1', '1. stupeň'), ('2', '2. stupeň'), ('3', '3. stupeň')], default='1', help_text='Výsledný stupeň rizikovosti', max_length=1)),
                ('patient_condition_change', models.BooleanField(default=False, help_text='Změna stavu pacienta')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical check in',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDekurz',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('made_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical dekurz',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='UNIS ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_number', models.CharField(db_index=True, max_length=10)),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical patient',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='UNIS ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_number', models.CharField(max_length=10, unique=True)),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('current_ambulance_care', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amubulance_patient', to='ipharm.care')),
                ('current_hospital_care', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_pacient', to='ipharm.care')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
