# Generated by Django 3.2.8 on 2021-10-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipharm', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.clinic'),
        ),
    ]
