# Generated by Django 3.2.9 on 2021-12-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipharm', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdrughistory',
            name='risk_diagnoses',
            field=models.ManyToManyField(blank=True, help_text='Seznam diagnóz', to='references.Diagnosis'),
        ),
        migrations.AddField(
            model_name='riskdrughistory',
            name='risk_drugs',
            field=models.ManyToManyField(blank=True, help_text='Seznam léčiv', to='references.Drug'),
        ),
        migrations.AddField(
            model_name='riskdrughistory',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Štítky', to='references.Tag'),
        ),
        migrations.AddField(
            model_name='pharmacologicalplancomment',
            name='pharmacological_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.pharmacologicalplan'),
        ),
        migrations.AddField(
            model_name='pharmacologicalplan',
            name='care',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipharm.care'),
        ),
        migrations.AddField(
            model_name='pharmacologicalplan',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Štítky', to='references.Tag'),
        ),
        migrations.AddField(
            model_name='pharmacologicalevaluation',
            name='care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.care'),
        ),
        migrations.AddField(
            model_name='pharmacologicalevaluation',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.drug'),
        ),
        migrations.AddField(
            model_name='pharmacologicalevaluation',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Štítky', to='references.Tag'),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.care'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_ambulance_care',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amubulance_patient', to='ipharm.care'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_hospital_care',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_pacient', to='ipharm.care'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.insurancecompany'),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorycomment',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.riskdrughistorycomment'),
        ),
    ]
