# Generated by Django 3.2.9 on 2021-11-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('ipharm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.insurancecompany'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='current_ambulance_care',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.care'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='current_hospital_care',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.care'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.patient'),
        ),
    ]
