# Generated by Django 3.2.9 on 2021-11-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('ipharm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.insurancecompany'),
        ),
    ]
