# Generated by Django 3.2.8 on 2021-11-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipharm', '0002_initial'),
        ('updates', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiagnosis',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.referenceupdate'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.clinic'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dekurz_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_dekurz', to='references.department'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dekurz_who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.person'),
        ),
        migrations.AddField(
            model_name='patient',
            name='department_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='references.department'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnoses',
            field=models.ManyToManyField(through='ipharm.PatientDiagnosis', to='references.Diagnosis'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.insurancecompany'),
        ),
        migrations.AddField(
            model_name='patient',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.referenceupdate'),
        ),
        migrations.AddField(
            model_name='historicalpatientdiagnosis',
            name='diagnosis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.diagnosis'),
        ),
        migrations.AddField(
            model_name='historicalpatientdiagnosis',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.patientdiagnosis'),
        ),
    ]
