# Generated by Django 3.2.11 on 2022-01-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_clinic_image'),
        ('ipharm', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UNIS ID'),
        ),
        migrations.AlterField(
            model_name='historicalcare',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UNIS ID'),
        ),
        migrations.AlterUniqueTogether(
            name='care',
            unique_together={('external_id', 'clinic')},
        ),
    ]
