# Generated by Django 3.2.8 on 2021-11-15 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0002_initial'),
        ('ipharm', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientdiagnosis',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatientdiagnosis',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.patient'),
        ),
        migrations.AddField(
            model_name='historicalpatientdiagnosis',
            name='update',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updates.referenceupdate'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='clinic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.clinic'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='dekurz_department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.department'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='dekurz_who',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.person'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='department_in',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.department'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.patient'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='insurance_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.insurancecompany'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='update',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='updates.referenceupdate'),
        ),
    ]
