# Generated by Django 3.2.11 on 2022-01-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_insurance_company_shortcut_unuque'),
        ('ipharm', '0004_care_external_id_and_clinic_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='care',
            name='diagnoses',
        ),
        migrations.AddField(
            model_name='checkin',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, help_text='Diagnóza', to='references.Diagnosis'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='diagnoses_drugs',
            field=models.ManyToManyField(blank=True, help_text='Seznam léčiv', related_name='drugs_checkins', to='references.Drug'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='diagnoses_note',
            field=models.TextField(blank=True, help_text='Poznámka'),
        ),
        migrations.AddField(
            model_name='historicalcheckin',
            name='diagnoses_note',
            field=models.TextField(blank=True, help_text='Poznámka'),
        ),
    ]
