# Generated by Django 3.2.11 on 2022-02-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0010_check_in_rename_for_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='current_care',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.care'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_care',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_current_care', to='ipharm.care'),
        ),
    ]
