# Generated by Django 3.2.12 on 2022-02-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_clinic_reference_id'),
        ('ipharm', '0015_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='in_insurance_report',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin',
            name='in_insurance_report',
        ),
        migrations.AddField(
            model_name='checkin',
            name='medical_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.medicalprocedure'),
        ),
        migrations.AddField(
            model_name='historicalcheckin',
            name='medical_procedure',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.medicalprocedure'),
        ),
    ]
