# Generated by Django 3.2.12 on 2022-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0017_care_external_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcare',
            name='doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
