# Generated by Django 3.2.12 on 2022-03-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0018_care_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalriskdrughistory',
            name='note',
            field=models.TextField(blank=True, help_text='Poznámka'),
        ),
        migrations.AddField(
            model_name='riskdrughistory',
            name='note',
            field=models.TextField(blank=True, help_text='Poznámka'),
        ),
    ]
