# Generated by Django 3.2.12 on 2022-03-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0020_pharmacological_evaluation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpharmacologicalevaluation',
            name='continuation',
            field=models.BooleanField(default=False, help_text='Pokračování v terapii'),
        ),
        migrations.AddField(
            model_name='historicalpharmacologicalevaluation',
            name='deployment',
            field=models.BooleanField(default=False, help_text='Nasazení léčiva'),
        ),
        migrations.AddField(
            model_name='historicalpharmacologicalevaluation',
            name='discontinuation',
            field=models.BooleanField(default=False, help_text='Vysazení léčiva'),
        ),
        migrations.AddField(
            model_name='historicalpharmacologicalevaluation',
            name='dose_change',
            field=models.BooleanField(default=False, help_text='Změna dávky'),
        ),
        migrations.AddField(
            model_name='pharmacologicalevaluation',
            name='continuation',
            field=models.BooleanField(default=False, help_text='Pokračování v terapii'),
        ),
        migrations.AddField(
            model_name='pharmacologicalevaluation',
            name='deployment',
            field=models.BooleanField(default=False, help_text='Nasazení léčiva'),
        ),
        migrations.AddField(
            model_name='pharmacologicalevaluation',
            name='discontinuation',
            field=models.BooleanField(default=False, help_text='Vysazení léčiva'),
        ),
        migrations.AddField(
            model_name='pharmacologicalevaluation',
            name='dose_change',
            field=models.BooleanField(default=False, help_text='Změna dávky'),
        ),
    ]
