# Generated by Django 3.2.12 on 2022-03-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0026_pharmacological_plan_medical_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpharmacologicalplancomment',
            name='verify',
        ),
        migrations.RemoveField(
            model_name='pharmacologicalplancomment',
            name='verify',
        ),
    ]
