# Generated by Django 3.2.12 on 2022-03-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0027_pharmacological_plan_comment_remove_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientinformation',
            name='file',
            field=models.TextField(blank=True, help_text='Soubor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='file',
            field=models.FileField(blank=True, help_text='Soubor', null=True, upload_to='patient_information/'),
        ),
    ]
