# Generated by Django 3.2.12 on 2022-04-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0028_patient_information_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_informations', to='ipharm.care'),
        ),
    ]
