# Generated by Django 3.2.12 on 2022-04-06 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_udpate_url_parameters'),
        ('references', '0023_department_remove_provider_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipharm', '0030_checkin_remove_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn_diagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.checkin')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.diagnosis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckIn_diagnoses_drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.checkin')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckIn_drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.checkin')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckIn_high_interaction_potential_drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.checkin')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckIn_narrow_therapeutic_window_drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.checkin')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCheckIn_narrow_therapeutic_window_drugs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checkin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.checkin')),
                ('drug', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.drug')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.checkin_narrow_therapeutic_window_drugs')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update')),
            ],
            options={
                'verbose_name': 'historical check in_narrow_therapeutic_window_drugs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCheckIn_high_interaction_potential_drugs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checkin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.checkin')),
                ('drug', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.drug')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.checkin_high_interaction_potential_drugs')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update')),
            ],
            options={
                'verbose_name': 'historical check in_high_interaction_potential_drugs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCheckIn_drugs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checkin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.checkin')),
                ('drug', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.drug')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.checkin_drugs')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update')),
            ],
            options={
                'verbose_name': 'historical check in_drugs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCheckIn_diagnoses_drugs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checkin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.checkin')),
                ('drug', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.drug')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.checkin_diagnoses_drugs')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update')),
            ],
            options={
                'verbose_name': 'historical check in_diagnoses_drugs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCheckIn_diagnoses',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checkin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.checkin')),
                ('diagnosis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.diagnosis')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.checkin_diagnoses')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update')),
            ],
            options={
                'verbose_name': 'historical check in_diagnoses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='checkin',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, help_text='Diagnóza', through='ipharm.CheckIn_diagnoses', to='references.Diagnosis'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='diagnoses_drugs',
            field=models.ManyToManyField(blank=True, help_text='Seznam léčiv', related_name='drugs_checkins', through='ipharm.CheckIn_diagnoses_drugs', to='references.Drug'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='drugs',
            field=models.ManyToManyField(blank=True, help_text='Seznam léčiv', related_name='drug_checkins', through='ipharm.CheckIn_drugs', to='references.Drug'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='high_interaction_potential_drugs',
            field=models.ManyToManyField(blank=True, help_text='Seznam léčiv s vysokým účinkovým tlakem', related_name='high_interaction_potential_checkins', through='ipharm.CheckIn_high_interaction_potential_drugs', to='references.Drug'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='narrow_therapeutic_window_drugs',
            field=models.ManyToManyField(blank=True, help_text='Seznam léčiv s úzkým terapeutickým oknem', related_name='narrow_therapeutic_window_checkins', through='ipharm.CheckIn_narrow_therapeutic_window_drugs', to='references.Drug'),
        ),
    ]
