# Generated by Django 3.2.12 on 2022-04-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0031_checkin_add_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacologicalevaluation',
            name='tags',
        ),
    ]
