# Generated by Django 3.2.12 on 2022-04-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0033_pharmacologicalevaluation_add_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacologicalplan',
            name='tags',
        ),
    ]
