# Generated by Django 3.2.12 on 2022-04-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0037_riskdrughistory_add_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpharmacologicalplancomment',
            name='verify',
            field=models.BooleanField(default=False, help_text='Vykázat ověření'),
        ),
        migrations.AddField(
            model_name='pharmacologicalplancomment',
            name='verify',
            field=models.BooleanField(default=False, help_text='Vykázat ověření'),
        ),
    ]
