# Generated by Django 3.2.13 on 2022-04-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0038_pharmaclological_plan_comment_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='toggle_diagnoses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcheckin',
            name='toggle_diagnoses',
            field=models.BooleanField(default=True),
        ),
    ]
