# Generated by Django 3.2.13 on 2022-06-01 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0023_department_remove_provider_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0004_model_update_created_at'),
        ('ipharm', '0040_patient_birth_date_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CheckInDiagnoses',
            },
        ),
        migrations.CreateModel(
            name='CheckInDiagnosisDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('check_in_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.checkindiagnosis')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCheckInDiagnosis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical check in diagnosis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCheckInDiagnosisDrug',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('check_in_diagnosis', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.checkindiagnosis')),
                ('drug', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.drug')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.checkindiagnosisdrug')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update')),
            ],
            options={
                'verbose_name': 'historical check in diagnosis drug',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='checkin_diagnoses_drugs',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='checkin_diagnoses_drugs',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses',
            name='history_relation',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses',
            name='update',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses_drugs',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses_drugs',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses_drugs',
            name='history_relation',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses_drugs',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcheckin_diagnoses_drugs',
            name='update',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='diagnoses',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='diagnoses_drugs',
        ),
        migrations.DeleteModel(
            name='CheckIn_diagnoses',
        ),
        migrations.DeleteModel(
            name='CheckIn_diagnoses_drugs',
        ),
        migrations.DeleteModel(
            name='HistoricalCheckIn_diagnoses',
        ),
        migrations.DeleteModel(
            name='HistoricalCheckIn_diagnoses_drugs',
        ),
        migrations.AddField(
            model_name='historicalcheckindiagnosis',
            name='check_in',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.checkin'),
        ),
        migrations.AddField(
            model_name='historicalcheckindiagnosis',
            name='diagnosis',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Diagnóza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.diagnosis'),
        ),
        migrations.AddField(
            model_name='historicalcheckindiagnosis',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.checkindiagnosis'),
        ),
        migrations.AddField(
            model_name='historicalcheckindiagnosis',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcheckindiagnosis',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update'),
        ),
        migrations.AddField(
            model_name='checkindiagnosis',
            name='check_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='ipharm.checkin'),
        ),
        migrations.AddField(
            model_name='checkindiagnosis',
            name='diagnosis',
            field=models.ForeignKey(help_text='Diagnóza', on_delete=django.db.models.deletion.CASCADE, to='references.diagnosis'),
        ),
        migrations.AddField(
            model_name='checkindiagnosis',
            name='drugs',
            field=models.ManyToManyField(blank=True, help_text='Seznam léčiv diagnózy', related_name='check_in_diagnoses', through='ipharm.CheckInDiagnosisDrug', to='references.Drug'),
        ),
        migrations.AlterUniqueTogether(
            name='checkindiagnosis',
            unique_together={('check_in', 'diagnosis')},
        ),
    ]
