# Generated by Django 3.2.13 on 2022-06-02 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0023_department_remove_provider_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0004_model_update_created_at'),
        ('ipharm', '0041_checkin_diagnoses_drugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRiskDrugHistoryDiagnosis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('diagnosis', models.ForeignKey(blank=True, db_constraint=False, help_text='Diagnóza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.diagnosis')),
            ],
            options={
                'verbose_name': 'historical risk drug history diagnosis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiskDrugHistoryDiagnosisDrug',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical risk drug history diagnosis drug',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RiskDrugHistoryDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('diagnosis', models.ForeignKey(help_text='Diagnóza', on_delete=django.db.models.deletion.CASCADE, to='references.diagnosis')),
            ],
            options={
                'verbose_name_plural': 'RiskDrugHistoryDiagnoses',
            },
        ),
        migrations.CreateModel(
            name='RiskDrugHistoryDiagnosisDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('check_in_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.riskdrughistorydiagnosis')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicalriskdrughistory_risk_drugs',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='historicalriskdrughistory_risk_drugs',
            name='history_relation',
        ),
        migrations.RemoveField(
            model_name='historicalriskdrughistory_risk_drugs',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalriskdrughistory_risk_drugs',
            name='riskdrughistory',
        ),
        migrations.RemoveField(
            model_name='historicalriskdrughistory_risk_drugs',
            name='update',
        ),
        migrations.RemoveField(
            model_name='riskdrughistory_risk_diagnoses',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='riskdrughistory_risk_diagnoses',
            name='riskdrughistory',
        ),
        migrations.RemoveField(
            model_name='riskdrughistory_risk_drugs',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='riskdrughistory_risk_drugs',
            name='riskdrughistory',
        ),
        migrations.RemoveField(
            model_name='riskdrughistory',
            name='risk_diagnoses',
        ),
        migrations.RemoveField(
            model_name='riskdrughistory',
            name='risk_drugs',
        ),
        migrations.DeleteModel(
            name='HistoricalRiskDrugHistory_risk_diagnoses',
        ),
        migrations.DeleteModel(
            name='HistoricalRiskDrugHistory_risk_drugs',
        ),
        migrations.DeleteModel(
            name='RiskDrugHistory_risk_diagnoses',
        ),
        migrations.DeleteModel(
            name='RiskDrugHistory_risk_drugs',
        ),
        migrations.AddField(
            model_name='riskdrughistorydiagnosis',
            name='drugs',
            field=models.ManyToManyField(blank=True, help_text='Seznam léčiv diagnózy', related_name='risk_drug_history_diagnoses', through='ipharm.RiskDrugHistoryDiagnosisDrug', to='references.Drug'),
        ),
        migrations.AddField(
            model_name='riskdrughistorydiagnosis',
            name='risk_drug_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='ipharm.riskdrughistory'),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorydiagnosisdrug',
            name='check_in_diagnosis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.riskdrughistorydiagnosis'),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorydiagnosisdrug',
            name='drug',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.drug'),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorydiagnosisdrug',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.riskdrughistorydiagnosisdrug'),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorydiagnosisdrug',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorydiagnosisdrug',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update'),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorydiagnosis',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ipharm.riskdrughistorydiagnosis'),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorydiagnosis',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorydiagnosis',
            name='risk_drug_history',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.riskdrughistory'),
        ),
        migrations.AddField(
            model_name='historicalriskdrughistorydiagnosis',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update'),
        ),
        migrations.AlterUniqueTogether(
            name='riskdrughistorydiagnosis',
            unique_together={('risk_drug_history', 'diagnosis')},
        ),
    ]
