# Generated by Django 3.2.13 on 2022-06-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0043_diagnoses_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cares', to='ipharm.patient'),
        ),
    ]
