from .adverse_effects import *
from .clinics import *
from .diagnoses import *
from .drugs import *
from .external_department import *
from .facilities import *
from .identifications import *
from .insurances import *
from .medical_procedures import *
from .persons import *
from .tags import *
