# Generated by Django 3.2.8 on 2021-10-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.IntegerField(db_index=True, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.BigIntegerField(db_index=True, unique=True)),
                ('patient_id', models.BigIntegerField(db_index=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'mužský'), ('FEMALE', 'ženský')], max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_number', models.CharField(max_length=20)),
                ('insurance_company', models.CharField(max_length=100)),
                ('insurance_number', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('department_in_id', models.IntegerField()),
                ('datetime_in', models.DateTimeField()),
                ('datetime_out', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.CharField(max_length=50)),
                ('dekurz_datetime', models.DateTimeField()),
                ('dekurz_who', models.IntegerField()),
                ('dekurz_department', models.IntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipharm.clinic')),
            ],
        ),
    ]
