# Generated by Django 3.2.8 on 2021-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipharm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('ambulance', 'Ambulance')], default='clinic', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalclinic',
            name='clinic_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('ambulance', 'Ambulance')], default='clinic', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalclinic',
            name='clinic_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='clinic',
            unique_together={('clinic_type', 'clinic_id')},
        ),
    ]
