# Generated by Django 3.2.9 on 2021-12-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_drugs'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ambulances',
            field=models.ManyToManyField(blank=True, related_name='ambulance_users', to='references.Clinic', verbose_name='My ambulances'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='hospital_users', to='references.Clinic', verbose_name='My hospitals'),
        ),
    ]
