# Generated by Django 3.2.12 on 2022-03-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportvariable',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalreportvariable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportvariable',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportvariable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='reportvariable',
            unique_together={('report_type', 'name'), ('report_type', 'description')},
        ),
    ]
