# Generated by Django 3.2.12 on 2022-04-05 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_variable_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericreporttype',
            name='frequency',
        ),
        migrations.AddField(
            model_name='genericreporttype',
            name='filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='genericreporttype',
            name='time_ranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
