# Generated by Django 3.2.12 on 2022-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_generic_report_type_filters_time_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericreportfile',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericreportfile',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgenericreportfile',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgenericreportfile',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genericreportfile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgenericreportfile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
