# Generated by Django 3.2.12 on 2022-04-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_generic_report_file_date_from_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericreportfile',
            name='time_range',
            field=models.CharField(default='custom', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalgenericreportfile',
            name='time_range',
            field=models.CharField(default='custom', max_length=255),
        ),
    ]
