# Generated by Django 3.2.12 on 2022-04-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_generic_report_type_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericreportfile',
            name='is_deleted',
        ),
        migrations.DeleteModel(
            name='HistoricalGenericReportFile',
        ),
    ]
