# Generated by Django 3.2.12 on 2022-04-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_generic_report_file_remove_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericreportfile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='genericreportfile',
            name='updated_at',
        ),
    ]
