# Generated by Django 3.2.13 on 2022-05-25 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('updates', '0003_udpate_url_parameters'),
        ('ipharm', '0040_patient_birth_date_index'),
        ('references', '0023_department_remove_provider_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_id', models.BigIntegerField()),
                ('type', models.CharField(choices=[('ipharm', 'ipharm'), ('delivery', 'delivery')], default='ipharm', max_length=50)),
                ('subtype', models.CharField(choices=[('ipharm_conciliation', 'ipharm_conciliation'), ('ipahrm_adverse_effect', 'ipharm_adverse_effect')], default='ipharm_conciliation', max_length=50)),
                ('state', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('refused', 'Refused'), ('solved', 'Solved')], default='created', max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='requisitions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_requisitions', to='references.person')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipharm.patient')),
                ('solver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solver_requisitions', to='references.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalRequisition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_id', models.BigIntegerField()),
                ('type', models.CharField(choices=[('ipharm', 'ipharm'), ('delivery', 'delivery')], default='ipharm', max_length=50)),
                ('subtype', models.CharField(choices=[('ipharm_conciliation', 'ipharm_conciliation'), ('ipahrm_adverse_effect', 'ipharm_adverse_effect')], default='ipharm_conciliation', max_length=50)),
                ('state', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('refused', 'Refused'), ('solved', 'Solved')], default='created', max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applicant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.person')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='requisitions.requisition')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipharm.patient')),
                ('solver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.person')),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.update')),
            ],
            options={
                'verbose_name': 'historical requisition',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
