# Generated by Django 3.2.13 on 2022-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_requisition_care'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequisition',
            name='file',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='file',
        ),
        migrations.AddField(
            model_name='historicalrequisition',
            name='file_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='file_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
