# Generated by Django 3.2.13 on 2022-06-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0004_requisition_file_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequisition',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='patient',
        ),
    ]
