name: Push workflow

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - local
      - staging
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache env files
        uses: actions/cache@v2
        with:
          path: ./.envs/
          key: envs-${{ github.sha }}
      - name:  Create env files
        run: |
          mkdir -p .envs/.development
          touch .envs/.development/.ipharm_app
          echo "SECRET_KEY=${{ secrets.SECRET_KEY_DEV }}" >>  .envs/.development/.ipharm_app
          touch .envs/.development/.ipharm_postgres
          echo POSTGRES_HOST=ipharm_postgres >>  .envs/.development/.ipharm_postgres
          echo POSTGRES_PORT=5432 >>  .envs/.development/.ipharm_postgres
          echo POSTGRES_DB=ipharm >>  .envs/.development/.ipharm_postgres
          echo POSTGRES_USER=ipharm >>  .envs/.development/.ipharm_postgres
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_DEV }}" >>  .envs/.development/.ipharm_postgres
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        uses: docker/bake-action@master
        with:
          files: docker-compose.development.yml
          push: false
          set: |
            *.cache-from=type=local,src=/tmp/.buildx-cache
            *.cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache env files
        uses: actions/cache@v2
        with:
          path: ./.envs/
          key: envs-${{ github.sha }}
      - name: Build image
        uses: docker/bake-action@master
        with:
          files: docker-compose.development.yml
          push: false
          set: |
            *.cache-from=type=local,src=/tmp/.buildx-cache
      - name: Build the stack
        run: docker-compose -f docker-compose.development.yml up -d
      - name: Test
        run: docker-compose -f docker-compose.development.yml run --rm -T app ./scripts/tests.sh

  isort:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache env files
        uses: actions/cache@v2
        with:
          path: ./.envs/
          key: envs-${{ github.sha }}
      - name: Build image
        uses: docker/bake-action@master
        with:
          files: docker-compose.development.yml
          push: false
          set: |
            *.cache-from=type=local,src=/tmp/.buildx-cache
      - name: Isort
        run: docker-compose -f docker-compose.development.yml run --rm -T app ./scripts/isort.sh

  black:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache env files
        uses: actions/cache@v2
        with:
          path: ./.envs/
          key: envs-${{ github.sha }}
      - name: Build image
        uses: docker/bake-action@master
        with:
          files: docker-compose.development.yml
          push: false
          set: |
            *.cache-from=type=local,src=/tmp/.buildx-cache
      - name: Black
        run: docker-compose -f docker-compose.development.yml run --rm -T app ./scripts/black.sh
