name: Release docker image

on:
  push:
    tags:
      - local
      - staging
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sets env vars for local
        run: |
          echo "DOCKER_IMAGE_NAME=conceptica/ipharm_app:local" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/local')
      - name: Sets env vars for staging
        run: |
          echo "DOCKER_IMAGE_NAME=conceptica/ipharm_app:staging" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/staging')
      - name: Sets env vars for release
        run: |
          echo "DOCKER_IMAGE_NAME=conceptica/ipharm_app:release" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/release')
      - name: Build image
        run: |
          export VERSION=$(cat version.txt)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./dockerfiles/production/Dockerfile
          push: true
          tags: ${{env.DOCKER_IMAGE_NAME}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          ls -a /tmp/
